//
// DO NOT MODIFY version.hpp, it is automatically generated by cmake
// The version is controlled in CMakeLists.txt
//

#ifndef SZ3_VERSION_HPP
#define SZ3_VERSION_HPP

#define SZ3_NAME "SZ3"
#define SZ3_VER  "3.1.7"
#define SZ3_VER_MAJOR 3
#define SZ3_VER_MINOR 1
#define SZ3_VER_PATCH 7
#define SZ3_VER_TWEAK 

#endif //SZ3_VERSION_HP
