os:
    - Visual Studio 2015

cache:
    - '%LOCALAPPDATA%\pip\Cache'

# fetch repository as zip archive
shallow_clone: true

environment:
    global:
        WIN_SDK_ROOT: "C:\\Program Files\\Microsoft SDKs\\Windows"

    matrix:
        # Python 3.7
        - BUILD_PY_PATH: "C:\\Python37-x64;C:\\Python37-x64\\Scripts"
          TEST_PY_PATH: "C:\\Python37-x64;C:\\Python37-x64\\Scripts"
          INSTALL_CMD: "python -m pip install --upgrade --pre"
          H5PY_OLDER_VERSION: "2.8.0"

        # Miniconda37
        - BUILD_PY_PATH: "C:\\Python37-x64;C:\\Python37-x64\\Scripts"
          TEST_PY_PATH: "C:\\Miniconda37-x64;C:\\Miniconda37-x64\\Library\\mingw-w64\\bin;C:\\Miniconda37-x64\\Library\\usr\\bin;C:\\Miniconda37-x64\\Library\\bin;C:\\Miniconda37-x64\\Scripts;C:\\Miniconda37-x64\\bin;C:\\Miniconda37-x64\\condabin"
          INSTALL_CMD: "conda install -y"
          H5PY_OLDER_VERSION: "2.8.0"


install:
    # Add Build Python to PATH
    - "SET OLD_PATH=%PATH%"
    - "SET PATH=%BUILD_PY_PATH%;%OLD_PATH%"

    # Upgrade distribution modules and dependencies
    - "python -m pip install --upgrade pip setuptools wheel h5py"

    # Print Python info
    - "python ci\\info_platform.py"
    - "pip freeze"


build_script:
    - "python setup.py bdist_wheel bdist_msi"
    - ps: "ls dist"


test_script:
    # Add Test Python to PATH
    - "SET PATH=%TEST_PY_PATH%;%OLD_PATH%"

    # Install dependencies
    - "%INSTALL_CMD% h5py"

    # Install the generated wheel package to test it
    # Make sure it does not come from cache or pypi
    # At this point all install_requires dependencies MUST be installed
    # as this is installing only from dist/
    - "pip install --pre --find-links dist/ --no-cache-dir --no-index hdf5plugin"

    # Test with latest h5py
    - "pip freeze"
    - "python test\\test.py"

    # Test with oldest available wheel of h5py
    - "%INSTALL_CMD% h5py==%H5PY_OLDER_VERSION%"
    - "pip freeze"
    - "python test\\test.py"


artifacts:
    # Archive the generated wheel package in the ci.appveyor.com build report.
    - path: dist\*
