
exclude = [
    "build",
    "vendorred",
]
line-length = 88

[lint]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "I",  # isort
    "S",  # flake8-bandit
    "W",
]

ignore = [
    "E501", # Line too long
]

[lint.per-file-ignores]
"test*.py" = ["S101"]  # assert
