name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_sdist:
    name: Build sdist & documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: python -m pip install --upgrade pip bandit black build flake8 isort mypy numpy twine
      - run: bandit -c pyproject.toml -r .
      - run: black --check .
      - run: flake8
      - run: isort --check .
      - run: mypy
      - run: python -m build --sdist
      - run: python -m twine check dist/*
      # Build documentation
      - run: sudo apt-get install pandoc
      - run: pip install "$(ls ./dist/hdf5plugin-*.tar.gz)[doc]"
        env:
          HDF5PLUGIN_STRIP: all  # Do not build the filters
      - run: sphinx-build --fail-on-warning --keep-going -b html doc/ ./html

  build_test:
    name: ${{ matrix.cibw_build }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            cibw_build: "cp39-win_amd64"
          - os: ubuntu-latest
            cibw_build: "cp312-manylinux_x86_64"
          - os: macos-latest
            cibw_build: "cp313-macosx_arm64"

    steps:
      - uses: actions/checkout@v5
      - uses: pypa/cibuildwheel@v3.1.4
        env:
          MACOSX_DEPLOYMENT_TARGET: "10.13"
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: ${{ matrix.cibw_build }}
          CIBW_TEST_EXTRAS: "test"
          # Test twice:
          # - with latest version
          # - with numpy v1 (for Python<=3.12) and oldest supported h5py
          CIBW_TEST_COMMAND: >
            python {project}/test/test.py &&
            pip install -r {project}/ci/oldest_h5py.txt &&
            python {project}/test/test.py
